[0m03:33:45.648407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002056B9C0750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020568B07D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002056CBD3450>]}


============================== 03:33:45.652942 | e2b921bb-0efd-406c-b004-c1ebca7260ea ==============================
[0m03:33:45.652942 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:33:45.653947 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'pipeline/transform/its_on_sale', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run --select price_events --profiles-dir pipeline/transform/its_on_sale', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m03:33:45.654951 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\meg\Documents\cam\proj\It's On Sale\its-on-sale-tracker\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:33:45.655955 [debug] [MainThread]: Command `dbt run` failed at 03:33:45.655955 after 0.09 seconds
[0m03:33:45.656959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002056CBEB0D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002056B9C0BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002056B940F50>]}
[0m03:33:45.657962 [debug] [MainThread]: Flushing usage events
[0m03:33:50.134011 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A6429E4510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A6419CB9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A641741150>]}


============================== 03:33:50.138275 | fb5ef813-c6d6-48cf-97bd-6f934792fea3 ==============================
[0m03:33:50.138275 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:33:50.139369 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'pipeline/transform/its_on_sale', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt test --select price_events --profiles-dir pipeline/transform/its_on_sale', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:33:50.140428 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\meg\Documents\cam\proj\It's On Sale\its-on-sale-tracker\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:33:50.141933 [debug] [MainThread]: Command `dbt test` failed at 03:33:50.141933 after 0.08 seconds
[0m03:33:50.141933 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A63A1E0AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A6419CB110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A6419CADD0>]}
[0m03:33:50.142951 [debug] [MainThread]: Flushing usage events
